### PR TITLE
Set relative_url for redhat-sigstore

### PR DESCRIPTION
**Pull request by breillyr**

### CODE REVIEW

**Comment by breillyr** [comment]
dock-pulp-bootstrap is currently in /bin so I would have to refactor it to create unit tests.

**Comment by twaugh** [comment]
How about the createRepo() change?

**Comment by breillyr** [comment]
CI failed but it passed locally (for 2.6 / 2.7)

**Comment by twaugh** [comment]
Maybe 'git push -f' again to kick it? Looks like Travis CI was just having a snooze.

**Comment by breillyr** [comment]
git push -f refuses to work ("Everything is up to date") so I'm just going to merge.

**Pull request merged**
