### PR TITLE
Remove references to legacy sigstore [CLOUDDST-7416]

### PR DESCRIPTION
**Pull request by neithere**
The legacy sigstore (a special Pulp repo) is not in use anymore.

### CODE REVIEW

**Comment by neithere** [comment]
Not sure why CI hasn't been triggered although it worked for an earlier PR.
I was unable to run Py3 tests locally and there was one locally failing py27 test even on `master`.

**Comment by emilyzheng** [comment]
`url = self.p.cdnhost + '/content/sigstore/'` at https://github.com/release-engineering/dockpulp/blob/master/dockpulp/__init__.py#L761 needs to be a pyxis url.

**Comment by neithere** [comment]
> `url = self.p.cdnhost + '/content/sigstore/'` at https://github.com/release-engineering/dockpulp/blob/master/dockpulp/__init__.py#L761 needs to be a pyxis url.

@emilyzheng would you suggest adding a config section in parallel with `filers`?

**Comment by emilyzheng** [comment]
> @emilyzheng would you suggest adding a config section in parallel with `filers`?

Yeah, that seems a good approach.

**Review by emilyzheng — APPROVED** [review]

**Pull request merged**
