### PR TITLE
Paginate repo contents to avoid pulp memory issues

### PR DESCRIPTION
**Pull request by lcarva**
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>

### CODE REVIEW

**Comment by lcarva** [comment]
@twaugh, @breillyr PTAL

**Comment by twaugh** [comment]
Do we care about the possibility of units we already saw being deleted before our request loop finishes?

**Comment by lcarva** [comment]
> Do we care about the possibility of units we already saw being deleted before our request loop finishes?

I don't know how to get around it.

**Comment by breillyr** [comment]
LGTM and tested locally, works as expected.

**Comment by twaugh** [comment]
> I don't know how to get around it.

Could adjust skip by less than the amount we received and check for expected overlap.

**Comment by breillyr** [comment]
>  Could adjust skip by less than the amount we received and check for expected overlap.

Even then there's no guarantee, a single image could have been removed at the start of the block for example. I'm not entirely sure how Pulp handles these requests without pagination, considering the time required to get responses back on large repos couldn't we have run into that issue already in the current implementation anyways?

**Comment by lcarva** [comment]
The same problem will occur with added content, which happens more frequently. Maybe for that case, we can limit the query by created timestamp?

What if result doesn't match up? Raise an exception?

**Comment by lcarva** [comment]
Also, pulp is quite weird with pagination. It seems to not always respect the limit option.

For example, if there are 40,000 content units in repo, I've seen the following:
1. Request 10,000 records with skip set to 0, pulp returns 10,000 records.
2. Request 10,000 records with skip set to 10,000, pulp returns 7,201 records.
3. Request 10,000 records with skip set to 17,201, pulp returns 10,000 records.
4. And so on until no records are returned.

I don't know why it returns less than what's requested in this case. 

Is paginating results potentially a dangerous change?

**Comment by twaugh** [comment]
I was thinking that if the overlap doesn't match up we'd decrease skip until we do see an overlap.

Maybe it should be possible to disable pagination for the dockpulp API call?

**Comment by lcarva** [comment]
> Maybe it should be possible to disable pagination for the dockpulp API call?

That makes sense. Default to enabled.

To summarize:

1. Pagination is optional - on by default
2. Query should use a timestamp to avoid picking up units added between page requests
3. Query should check for overlap to handle units deleted between page requests

For third item, I'm wondering if we should restart the whole query if overlap check fails. My concern with increasing overlap by one and retrying is that we may get stuck in a loop where we're hitting the server hundreds of times (think garbage collection). Restarting the whole query should only be attempted 3(?) times before dock-pulp fails out.

Thoughts?

**Comment by twaugh** [comment]
Yes, let's restart the query a limited number of times. That all looks good.

**Comment by breillyr** [comment]
Looks good to me.

**Comment by lcarva** [comment]
I can't get a successful run with the overlap check because assertion seems to randomly fail.
Tried explicit sorting but that didn't change the outcome. Pushed commit so you can see where I'm at.

**Comment by lcarva** [comment]
It appears that the overlap check fails in the case where pulp returns less items than were requested as I mentioned in https://github.com/release-engineering/dockpulp/pull/189#issuecomment-414686067.
Digging further.

**Comment by lcarva** [comment]
Alright, I figured out the oddness with overlap. Bad code on my end. Also, the issue where pulp returns less items than requested appears to be on my end, too.

So... with the latest commit, pagination works as expected with the 3 constraints mentioned earlier. However, I'm only getting `docker_blob` content units. Any ideas?

**Comment by lcarva** [comment]
Filed pulp [issue](https://pulp.plan.io/issues/3931) for the odd behavior mentioned on my previous comment.

We could either not perform the query with an overlap (seems to work, actually), or make an additional request to ensure we're done with fetching results. 

I'll play with the second one for a bit.

**Comment by twaugh** [comment]
The other option is to add a new dockpulp method, perhaps a generator, to just naively page through the results.

Then callers who don't care about having a complete point-in-time view can just step through each result.

Speaking of which, which callers are likely to want naive paging, vs fetch-everything-at-once?

**Comment by lcarva** [comment]
I change the algorithm so if the amount of items returned is less than `limit`, another request is made without overlap. This successfully gets around the pulp issue. The downside is that an additional request is always made. This is probably ok.

Even with pagination though I still can't list contents of `redhat-everything`. It fails after a few pages with 500 error.

**Comment by lcarva** [comment]
500 error was due to sorting, which apparently pulp doesn't like. Removed it and everything seems fine.

PR is ready for a review.

**Pull request merged**
